# lastest docker compose version
version: '3.8'
# all containers to be created
services:
  # container name
  db:
    image: postgres
    ports:
      # HOST:CONTAINER
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=car_data # creates database
    # use volumes to allow data persistence
    volumes:
      # name of the volume:path on host
      - postgres-data:/var/lib/postgresql/data
  server:
    # start webserver after database is up
    depends_on:
      - db
    # build the image from the Dockerfile
    build: .
    # name of the created image
    image: go-postgres-webserver
    ports:
      - "5000:5000"
    environment:
      - DIALECT=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=car_data

volumes:
  postgres-data:
    driver: local